//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Life_Cost
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit
    {
        public string st_id { get; set; }
        public string accNumber { get; set; }
        public decimal value { get; set; }
        public string day { get; set; }
        public string month { get; set; }
        public string year { get; set; }
        public int dep_id { get; set; }
    
        public virtual BankAcc BankAcc { get; set; }
        public virtual student student { get; set; }
    }
}
